"""posts tables

Revision ID: 14b9329385e9
Revises: f8decec9df82
Create Date: 2018-10-10 14:37:29.650701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b9329385e9'
down_revision = 'f8decec9df82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=4000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_post_timestamp'), 'news_post', ['timestamp'], unique=False)
    op.create_table('secure_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=4000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secure_post_timestamp'), 'secure_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secure_post_timestamp'), table_name='secure_post')
    op.drop_table('secure_post')
    op.drop_index(op.f('ix_news_post_timestamp'), table_name='news_post')
    op.drop_table('news_post')
    # ### end Alembic commands ###
