"""posts tables

Revision ID: 424cecfd7409
Revises: 14b9329385e9
Create Date: 2018-10-10 14:39:23.186416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424cecfd7409'
down_revision = '14b9329385e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_post', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('secure_post', sa.Column('title', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secure_post', 'title')
    op.drop_column('news_post', 'title')
    # ### end Alembic commands ###
